name: SpellsPlus
main: austxnsheep.spellsplus.Main
version: 1.19
api-version: 1.19
author: Austxnsheep

commands:
  spellsPlus:
    description: Used for allowing admins to change things
    usage: /spellsplus
    permission: SpellsPlus.admin

worlds:
  arcanum:
    generator: CustomChunkMaker