name: SpellsPlus
version: '${project.version}'
main: austxnsheep.spellsplus.Main
api-version: 1.19
author: Austxnsheep

commands:
  spawnParticle:
    description: A test to see if this plugin is working (spells plus)
    usage: /spawnParticle
    permission: SpellsPlus.spawnParticles
  addSpell:
    description: A admin command to add spells to any item
    usage: /addspell <spell name> <mana cost>
    permission: SpellsPlus.addSpell
  setMana:
    description: Sets the mana of a specified player
    usage: /setMana <Player name> <Amount of mana>
    permission: SpellsPlus.setMana